In [4]:
library(tidyverse)
library(readr)
library(knitr)
library(skimr)

In [24]:
Resident <- read.csv(file = "Estimat Resident Population .csv") #read csv

In [25]:
Resident

    Estimated.Resident.Population..Mean.Quarter.Ended..by.Sex..1991....Qrtly.Mar.Jun.Sep.Dec.
1
2   1991Q1
3   1991Q2
4   1991Q3
5   1991Q4
6   1992Q1
7   1992Q2
8   1992Q3
9   1992Q4
10  1993Q1
11  1993Q2
12  1993Q3
13  1993Q4
14  1994Q1
15  1994Q2
16  1994Q3
17  1994Q4
18  1995Q1
19  1995Q2
20  1995Q3
21  1995Q4
22  1996Q1
23  1996Q2
24  1996Q3
25  1996Q4
26  1997Q1
27  1997Q2
28  1997Q3
29  1997Q4
30  1998Q1
⋮   ⋮
94  2014Q1
95  2014Q2
96  2014Q3
97  2014Q4
98  2015Q1
99  2015Q2
100 2015Q3
101 2015Q4
102 2016Q1
103 2016Q2
104 2016Q3
105 2016Q4
106 2017Q1
107 2017Q2
108 2017Q3
109 2017Q4
110 2018Q1
111 2018Q2
112 2018Q3
113 2018Q4
114 2019Q1
115 2019Q2
116 2019Q3
117 2019Q4
118 2020Q1
119 2020Q2
120 2020Q3
121 2020Q4
122 2021Q1
123 2021Q2
    X       X.1     X.2
1   Male    Female  Total
2   1712100 1769500 3481500
3   1717300 1774200 3491500
4   1721700 1778200 3499900
5   1727100 1783200 3510300
6   1733000 1788200 3521300
7   1737500 1791600 3529100
8   1741000 1794600 3535600
9   1746100 1799900 3545900
10  1752300 1806100 3558300
11  1757400 1810900 3568300
12  1762200 1815400 3577500
13  1768700 1821700 3590400
14  1776000 1828700 3604700
15  1781700 1834100 3615700
16  1786800 1839200 3625900
17  1793800 1846300 3640100
18  1801800 1854200 3656000
19  1808300 1860200 3668500
20  1814800 1866300 3681000
21  1823400 1874300 3697700
22  1832400 1882700 3715000
23  1839000 1888700 3727700
24  1844400 1894400 3738800
25  1851500 1902500 3753900
26  1858400 1910400 3768800
27  1862500 1915800 3778300
28  1865800 1920500 3786300
29  1870400 1926500 3797000
30  1874800 1932200 3807000
⋮   ⋮       ⋮       ⋮
94  2199300 2289900 4489200
95  2210900 2297900 4508800
96  2222800 2305500 4528400
97  2236900 2315500 4552300
98  2251700 2326400 4578100
99  2264900 2335800 4600600
100 2277700 2345100 4622800
101 2292900 2357100 4650000
102 2309000 2370400 4679400
103 2323000 2381500 4704600
104 2335800 2391800 4727700
105 2350200 2404200 4754400
106 2365200 2417000 4782200
107 2377900 2427300 4805200
108 2388700 2436200 4824900
109 2401100 2446800 4847900
110 2414800 2458100 4872800
111 2426100 2467200 4893400
112 2435500 2475400 4911000
113 2445900 2485400 4931300
114 2457300 2496000 4953300
115 2467300 2504900 4972300
116 2478200 2514800 4993100
117 2493900 2529800 5023700
118 2513000 2548700 5061600
119 2525300 2561200 5086500
120 2529400 2565400 5094800
121 2533200 2569700 5102900
122 2536500 2573200 5109700
123 2540400 2577400 5117800

In [5]:
Estimat_Resident_Population <- read.csv('migrant.csv')

In [6]:
Estimat_Resident_Population

   year
1  2005
2  2006
3  2007
4  2008
5  2009
6  2010
7  2011
8  2012
9  2013
10 2014
11 2015
12 2016
13 2017
14 2018
15 2019
16 2020
17 Table information:
18 Units:
19 Number, Magnitude = Units
20
21 Footnotes:
22 The standard error indicates the uncertainty of the provisional migration estimate. For example, the 95 percent confidence interval is +/-1.96 standard errors.
23 These intervals reflect the model uncertainty, not the extent of future revisions to provisional data. Standard errors are non-additive.
24 Owing to rounding, individual figures may not sum to stated totals.
25 Visa type is available from July 2003
26 The immigration visa type is that held or granted on arrival in New Zealand. People may change their visa type while still in New Zealand.
27
28 Symbols:
29 .. figure not available
30 C: Confidential
31 E: Early Estimate
32 P: Provisional
33 R: Revised
34 S: Suppressed
35
36 Status flags are not displayed
37
38 Table reference:
39 ITM492AA
40
41 Last updated:
42 10 September 2021 10:45am
43
44 Source: Statistics New Zealand
45 Contact: Information Centre
46 Telephone: 0508 525 525
47 Email:info@stats.govt.nz
   Residence.Total.All.Countries.of.Last.Permanent.Residence
1  18457
2  19367
3  16758
4  15965
5  14818
6  13535
7  13784
8  13852
9  13508
10 14511
11 14982
12 17161
13 15601
14 13268
15 14499
16  7490
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
31    NA
32    NA
33    NA
34    NA
35    NA
36    NA
37    NA
38    NA
39    NA
40    NA
41    NA
42    NA
43    NA
44    NA
45    NA
46    NA
47    NA
   Student.Total.All.Countries.of.Last.Permanent.Residence
1   8058
2   9534
3  12563
4  16214
5  16114
6  17015
7  16774
8  16145
9  16444
10 25323
11 30062
12 25866
13 25210
14 24664
15 26744
16 10565
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
31    NA
32    NA
33    NA
34    NA
35    NA
36    NA
37    NA
38    NA
39    NA
40    NA
41    NA
42    NA
43    NA
44    NA
45    NA
46    NA
47    NA
   Visitor.Total.All.Countries.of.Last.Permanent.Residence
1  28609
2  30498
3  32118
4  33620
5  23731
6  19840
7  19689
8  18092
9  18102
10 21269
11 23545
12 26814
13 25516
14 26843
15 32992
16 16199
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
31    NA
32    NA
33    NA
34    NA
35    NA
36    NA
37    NA
38    NA
39    NA
40    NA
41    NA
42    NA
43    NA
44    NA
45    NA
46    NA
47    NA
   Work.Total.All.Countries.of.Last.Permanent.Residence
1  11221
2  13882
3  15900
4  17451
5  14731
6  13406
7  15603
8  17705
9  20317
10 22026
11 24926
12 26111
13 29183
14 31866
15 39742
16 12968
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
31    NA
32    NA
33    NA
34    NA
35    NA
36    NA
37    NA
38    NA
39    NA
40    NA
41    NA
42    NA
43    NA
44    NA
45    NA
46    NA
47    NA
   New.Zealand.and.Australian.citizens TOTAL
1  36478                               103982
2  36177                               110687
3  34982                               113450
4  35237                               119994
5  37349                               108265
6  35613                               100499
7  33261                               100206
8  34685                               101762
9  40520                               110282
10 43572                               128180
11 45165                               140125
12 45996                               143124
13 43513                               140102
14 41344                               139016
15 48461                               165742
16 37887                                88768
17    NA                                   NA
18    NA                                   NA
19    NA                                   NA
20    NA                                   NA
21    NA                                   NA
22    NA                                   NA
23    NA                                   NA
24    NA                                   NA
25    NA                                   NA
26    NA                                   NA
27    NA                                   NA
28    NA                                   NA
29    NA                                   NA
30    NA                                   NA
31    NA                                   NA
32    NA                                   NA
33    NA                                   NA
34    NA                                   NA
35    NA                                   NA
36    NA                                   NA
37    NA                                   NA
38    NA                                   NA
39    NA                                   NA
40    NA                                   NA
41    NA                                   NA
42    NA                                   NA
43    NA                                   NA
44    NA                                   NA
45    NA                                   NA
46    NA                                   NA
47    NA                                   NA